export const SERVICEABILITY_CONTENT_URL = "/serviceability-content-select"
export const SERVICEABILITY_CODE_APPROACHES_URL = "/serviceability-code-approaches"
export const ULTIMATE_URL = "/main-selection-two"
export const MAIN_SELECTION_THREE = "/main-selection-three"
export const LESSON_PAGE = "/lesson"
export const CALCULATION_PAGE = "/calculation"
export const LIST_SCREEN_PAGE = "/list"
export const COMPARE_PAGE = "/compare"
export const CODE_SELECTION = "/select-code"


export const CALCULATION_SERVICEABILITY_CW_BSI = "/serviceability-crack-width-bsi-calculation"
export const CALCULATION_SERVICEABILITY_CW_EC = "/serviceability-crack-width-ec-calculation"
export const CALCULATION_SERVICEABILITY_DF_BSI = "/serviceability-deflection-bsi-calculation"
export const CALCULATION_SERVICEABILITY_DF_EC = "/serviceability-deflection-ec-calculation"
export const DEFLECTION_SIMPLIFIED_CALCULATION = "/deflection-simplified-calculation"
